# Generated by Django 3.0.7 on 2021-01-05 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(blank=True, choices=[('cameras', 'cameras'), ('drones', 'drones'), ('recorders', 'recorders'), ('lighting', 'lighting'), ('other', 'other')], default=('other', 'other'), max_length=100, null=True),
        ),
    ]
