# Generated by Django 3.0.7 on 2021-01-05 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='gender',
            new_name='product_type',
        ),
    ]
