# Generated by Django 3.0.7 on 2021-01-08 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='aspect_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='colour_filter',
            field=models.CharField(blank=True, default='Standard', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='depth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='detail_one',
            field=models.CharField(default='EDIT ME', max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='detail_three',
            field=models.CharField(default='EDIT ME', max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='detail_two',
            field=models.CharField(default='EDIT ME', max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='pixels',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='spec_type',
            field=models.CharField(blank=True, default='Standard', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='title_one',
            field=models.CharField(default='EDIT ME', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='title_two',
            field=models.CharField(default='EDIT ME', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
