# Generated by Django 3.0.7 on 2021-01-08 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20210108_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='aspect_ratio',
            field=models.CharField(blank=True, default='3:2', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='depth',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='detail_one',
            field=models.CharField(default='Erat nam at lectus urna duis convallis convallis tellus id interdum velit laoreet id donec ultrices tincidunt arcu non sodales neque. d donec ultrices tincidunt arcu non sodales neque. tincidunt arcu non sodales neque.', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='detail_three',
            field=models.CharField(default='Erat nam at lectus urna duis convallis convallis tellus id interdum velit laoreet id donec ultrices tincidunt arcu non sodales.', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='detail_two',
            field=models.CharField(default='Erat nam at lectus urna duis convallis convallis tellus id interdum velit laoreet id donec ultrices tincidunt arcu non sodales.', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='height',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='spec_type',
            field=models.CharField(blank=True, default='Compact', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='title_one',
            field=models.CharField(default='The Best Quality Photos', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='title_two',
            field=models.CharField(default='Long Lasting Battery', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.IntegerField(blank=True, default=175, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='width',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
    ]
